/**
 * GENERATED by `node src/components/bottle3d/tools/extract.mjs` — do not edit.
 *
 * Everything here was read out of the product photography in
 * `public/products/`: the juice colours are median samples off each bottle,
 * and the asset paths point at crops taken from the same frames. Regenerate
 * rather than tweak — a hand-edited value here stops matching the photo it
 * claims to come from, which is the entire point of the file.
 */

export interface PhotoFruit {
  src: string;
  /** Resting position in world units: x across, y up, z towards the camera. */
  x: number;
  y: number;
  z: number;
  /** World-unit width of the sprite. */
  size: number;
  /** Resting roll, radians. */
  roll: number;
  /** Multiplies the drift and spin rates, so no two pieces keep time. */
  rate: number;
}

export interface PhotoAssets {
  /** Median of the lit body above the sticker. */
  accent: string;
  /** Median of the deep liquid either side of the sticker. */
  accentDeep: string;
  /** The real sticker, unwrapped off the bottle's cylinder. */
  label: string;
  fruit: PhotoFruit[];
}

export const PHOTO_ASSETS: Record<string, PhotoAssets> = {
  "classic-orange": {
    accent: "#D28207",
    accentDeep: "#C16802",
    label: "/bottle3d/label-classic-orange.png",
    fruit: [

    ],
  },
  "apple": {
    accent: "#979C0E",
    accentDeep: "#7A8502",
    label: "/bottle3d/label-apple.png",
    fruit: [

    ],
  },
  "pineapple": {
    accent: "#BD7315",
    accentDeep: "#A05205",
    label: "/bottle3d/label-pineapple.png",
    fruit: [

    ],
  },
  "orange-carrot": {
    accent: "#D8680C",
    accentDeep: "#C34402",
    label: "/bottle3d/label-orange-carrot.png",
    fruit: [

    ],
  },
  "watermelon": {
    accent: "#C1403F",
    accentDeep: "#AC1421",
    label: "/bottle3d/label-watermelon.png",
    fruit: [

    ],
  },
  "pomegranate": {
    accent: "#7F2020",
    accentDeep: "#5C080E",
    label: "/bottle3d/label-pomegranate.png",
    fruit: [

    ],
  },
  "mango": {
    accent: "#D88A15",
    accentDeep: "#C56605",
    label: "/bottle3d/label-mango.png",
    fruit: [

    ],
  },
};
